linters:
    Comment:
        enabled: false
    StringQuotes:
        enabled: false
    Indentation:
        width: 4
    IdSelector:
        enabled: false
    VendorPrefix:
        enabled: false
