#!/bin/bash

tput civis
tput bold
clear

while true
do
  HOME=$(tput cup 0 0)
  ED=$(tput ed)
  printf '%s% 4s' "Battery: " $(pmset -g batt | grep -Eo "\d+%")
  printf '%s%s' "$HOME" "$ED"
  sleep 30
done
