#!/bin/bash

tput civis
while true
do
  clear
  pmset -g batt | grep -Eo "\d+%"
  tput cuu1
  sleep 30

  read -t 0.25 -N 1 input
  if [[ $input = "q" ]] || [[ $input = "Q" ]]; then
  # The following line is for the prompt to appear on a new line.
    echo
    tput cnorm
    break
  fi
done
